### ISSUE TITLE
Could you share the origin file of the stl you put on thingiverse?

### ISSUE THREAD

**Issue by 10bn** [drGarbinsky/dactylmanu-ball#1]
Hi, I found your great creation on thingiverse and would like to ask you if you could share the cad creation file?

**Comment by drGarbinsky** [comment]
sorry for the late reply. I only   have the 3mf file as I hacked that out in MS 3d Builder. And after using mine for a while I don't think those trackballs are that good. I am working on a v2 with laser tracked input.

**Comment by 10bn** [comment]
What kind of hardware do you have in mind for the laser tracking?

**Comment by drGarbinsky** [comment]
https://www.tindie.com/products/jkicklighter/pmw3389-motion-sensor/
